### ISSUE TITLE
Darkmode color option

### ISSUE THREAD

**Issue by janoschdigg** [jacksleight/statamic-lazy-logo#4]
Currently there is no option to set a different color for the new CP darkmode.

It would be nice to be able to define 2 different Colors based on the selected mode :)

**Comment by jacksleight** [comment]
Hey, I was thinking I might retire this addon, as core has this [built in](https://github.com/statamic/cms/pull/10350) now (and that supports dark mode).

But if that doesn't quite do what you need I'm happy to look at updating this.

**Comment by janoschjost** [comment]
Hi jack im sorry i actually didn't know this feature is part of core now :) in this case my question is useless sorry! thanks for your reply
